const numbers = [
    { digit: 1, corean: '하나 (hana)', sinocorean: '일 (il)' },
    { digit: 2, corean: '둘 (dul)', sinocorean: '이 (i)' },
    { digit: 3, corean: '셋 (set)', sinocorean: '삼 (sam)' },
    { digit: 4, corean: '넷 (net)', sinocorean: '사 (sa)' },
    { digit: 5, corean: '다섯 (daseot)', sinocorean: '오 (o)' },
    { digit: 6, corean: '여섯 (yeoseot)', sinocorean: '육 (yuk)' },
    { digit: 7, corean: '일곱 (ilgop)', sinocorean: '칠 (chil)' },
    { digit: 8, corean: '여덟 (yeodeol)', sinocorean: '팔 (pal)' },
    { digit: 9, corean: '아홉 (ahop)', sinocorean: '구 (gu)' },
    { digit: 10, corean: '열 (yeol)', sinocorean: '십 (ship)' },
];

const concepts = [
    { name: 'Ion-bi-ryu', meaning: 'Escuela o Estilo de los Secretos de la Golondrina' },
    { name: 'Do-yang', meaning: 'Gimnasio o lugar de práctica' },
    { name: 'Ma-ru', meaning: 'Recinto o superficie sobre la cual se practica' },
    { name: 'Sabon', meaning: 'Profesor' },
    { name: 'Sabon-nim', meaning: 'Maestro' },
    { name: 'Chong-che-nim', meaning: 'Presidente de la Liga o Asociación' },
    { name: 'Kwan-jang-nim', meaning: 'Gran Maestro' },
    { name: 'Cho-kio', meaning: 'Ayudante del profesor' },
    { name: 'Che-ya', meaning: 'Alumno' },
    { name: 'Do-bok', meaning: 'Uniforme' },
    { name: 'Cha-riot', meaning: 'Firmes' },
    { name: 'Hieit', meaning: 'Saludo' },
    { name: 'Coman', meaning: 'Descanso (atención); pies ancho de hombros' },
    { name: 'Bal-bolio-sung-ma-se', meaning: 'Posición de jinete (puños a los costados)' },
    { name: 'Kwon-do-no-kuol-sung-ma-se', meaning: 'Posición de jinete (puños sobre la cintura)' },
    { name: 'Son-olio-yumbi', meaning: 'Brazos a 90º' },
    { name: 'Yon-yin-dong-yak-yumbi', meaning: 'Posición de avance (manos a la cintura); pies ancho de hombros' },
    { name: 'Bal-chagui', meaning: 'Posición de patada' },
    { name: 'Fal-bakuo', meaning: 'Cambio de brazos (fal:brazos)' },
    { name: 'Bal-bakuo', meaning: 'Cambio de piernas (bal:piernas)' },
    { name: 'Kiap', meaning: 'Grito' },
    { name: 'Di', meaning: 'Atrás' },
    { name: 'Di-dora', meaning: 'Giro atrás' },
    { name: 'Du-bun-yirigui', meaning: 'Dos veces, segundo con grito' },
    { name: 'Ki-bon-dong-yak', meaning: 'Forma básica' },
    { name: 'Su-rion', meaning: 'Práctica' },
    { name: 'De-rion', meaning: 'Lucha' },
    { name: 'Kong-kiok', meaning: 'Ataque' },
    { name: 'Bang-o', meaning: 'Defensa' },
    { name: 'Hiong', meaning: 'Forma' },
    { name: 'Ho-sin-sul', meaning: 'Defensa personal' },
    { name: 'Il-su-derion', meaning: 'Lucha a un paso' },
    { name: 'I-su-derion', meaning: 'Lucha a dos pasos' },
    { name: 'Sam-su-derion', meaning: 'Lucha a tres pasos' },
    { name: 'Ban-cha-iu-derion', meaning: 'Media lucha' },
    { name: 'Cha-iu-derion', meaning: 'Lucha libre (combate)' },
    { name: 'Sang-bu', meaning: 'Arriba' },
    { name: 'Chung-bu', meaning: 'Centro' },
    { name: 'Ja-bu', meaning: 'Abajo' },
    { name: 'Ne-su', meaning: 'Interior' },
    { name: 'We-su', meaning: 'Exterior' },
];

const hiong = [
    { name: '1. Ion-ki-il-sik', meaning: 'Hiong 1 – Formas inferiores' },
    { name: '2. Ion-ki-i-sik', meaning: 'Hiong 2 – Formas inferiores' },
    { name: '3. Ion-ki-sam-sik', meaning: 'Hiong 3 – Formas inferiores' },
    { name: '4. Ion-cho-il-hyun', meaning: 'Hiong 1 – Formas inferiores' },
    { name: '5. Ion-cho-i-hyun', meaning: 'Hiong 2 – Formas inferiores' },
    { name: '6. Ion-cho-sam-hyun', meaning: 'Hiong 3 – Formas inferiores' },
    { name: '7. Ion-cho-sa-hyun', meaning: 'Hiong 4 – Formas inferiores' },
    { name: '8. Ion-cho-o-hyun', meaning: 'Hiong 5 – Formas inferiores' },
    { name: '9. Ion-cho-ryuk-hyun', meaning: 'Hiong 6 – Formas superiores' },
];

const handKicks = [
    { name: 'Chong-kwon-kong-kiok', meaning: 'Golpe de puño al esófago' },
    { name: 'Ka-kwon', meaning: 'Golpe de puño transversal a la cara' },
    { name: 'Il-chi-kwon', meaning: 'Golpe de puño con nudillo de dedo medio' },
    { name: 'Kwon-do-no-kuol', meaning: 'Golpe con canto de puño a la cintura' },
    { name: 'Iok-kwon-do', meaning: 'Golpe con el canto interior del puño' },
    { name: 'Kuan-su-miong-hi', meaning: 'Punta de dedos al esófago' },
    { name: 'Kuan-su-se-wuo', meaning: 'Punta de dedos a la tráquea' },
    { name: 'Su-do-mok-chigui', meaning: 'Golpe con canto de mano al cuello' },
    { name: 'Iok-su-do', meaning: 'Golpe con canto interior de mano a la sien' },
    { name: 'Yang-kong-kiok', meaning: 'Golpe con palma de mano a la cara' },
    { name: 'Iu-kwon-nupio', meaning: 'Golpe de nudillo al tabique nasal' },
    { name: 'Iu-kwon-se-wuo', meaning: 'Golpe de nudillo al esófago' },
    { name: 'Il-yi-an-kong-kiok', meaning: 'Un dedo al ojo' },
    { name: 'I-yi-an-kong-kiok', meaning: 'Dos dedos a los ojos' },
    { name: 'Sam-yi-kong-kiok', meaning: 'Tres dedos a los ojos' },
    { name: 'Sa-yi-kong-kiok', meaning: 'Cuatro dedos a los ojos' },
    { name: 'O-yi-kuan-su', meaning: 'Cinco dedos a los ojos' },
    { name: 'Hap-yi-kong-kiok', meaning: 'Tres dedos a la sien' },
    { name: 'Dung-yu-mok-o-ligui', meaning: 'Golpe con dorso de muñeca al mentón' },
    { name: 'Mok-chigui', meaning: 'Golpe con mano en ataque a la tráquea' },
    { name: 'Fal-kum-chi-kong-kiok', meaning: 'Golpe con codo en ataque a la cara' },
    { name: 'Fal-kum-chi-chigui', meaning: 'Golpe con codo ascendente en ataque al mentón' },
    { name: 'Kama-chigui', meaning: 'Agarre de pelo' },
];

const defenses = [
    { name: 'Yang-bang-o', meaning: 'Defensa con palma de mano a la cara' },
    { name: 'Yang-nul-lo-bang-o', meaning: 'Defensa descendente con palma de mano' },
    { name: 'Yang-olio-bang-o', meaning: 'Defensa ascendente con palma de mano' },
    { name: 'Chung-bu-yang-bang-o', meaning: 'Defensa con palma de mano a altura media' },
    { name: 'Ja-bu-yang-bang-o', meaning: 'Defensa con palma de mano a genitales' },
    { name: 'Fion-su-do-bang-o', meaning: 'Defensa en abanico a la cara' },
    { name: 'We-bang-o', meaning: 'Defensa con antebrazo de adentro hacia afuera' },
    { name: 'Ne-bang-o', meaning: 'Defensa con antebrazo de afuera hacia adentro' },
    { name: 'Sang-bu-bang-o', meaning: 'Defensa con antebrazo ascendente' },
    { name: 'Ja-bu-bang-o', meaning: 'Defensa con antebrazo descendente' },
];

const forwardPositionsMessage = 'Cualquiera de estas formas se combinan con: Sung-ma-se o Bal-chagui';

const forwardPositions = [
    { name: 'Yon-yin-dong-yak-yumbi', meaning: 'Manos a la cintura' },
    { name: 'Kwon-do-no-kuol-yon-yin-dong-yak-yumbi', meaning: 'Canto de puños a la cintura' },
    { name: 'Sang-bu-yon-yin-dong-yak-yumbi', meaning: 'Canto de puños a la altura del pecho' },
    { name: 'Su-piong-yon-yin-dong-yak-yumbi', meaning: 'Firmes; brazos flexionados frente al pecho' },
    { name: 'Yon-ju-bo-yon-yin-dong-yak-yumbi', meaning: 'Brazo derecho flexionado frente al pecho y brazo izquierdo flexionado atrás en la cintura' },
];

const legKicks = [
    { name: 'Mu-rob', meaning: 'Golpe con la rodilla' },
    { name: 'Ap-chagui (yok-yi-sang-bu)', meaning: 'Patada frontal recta con dedos hacia arriba' },
    { name: 'Ap-coco-chagui', meaning: 'Patada frontal con flexión de rodilla' },
    { name: 'Bacat-dolio-chagui', meaning: 'Patada frontal circular recta hacia afuera' },
    { name: 'An-dolio-chagui', meaning: 'Patada frontal circular recta hacia adentro' },
    { name: 'Chik-o-chagui', meaning: 'Patada frontal recta descendente con talón' },
    { name: 'Iob-chagui', meaning: 'Patada lateral con talón o canto de pie' },
    { name: 'Dolio-chagui', meaning: 'Patada circular con empeine o metatarso' },
    { name: 'Cofo-chagui', meaning: 'Patada doble' },
    { name: 'Ti-chagui', meaning: 'Patada hacia atrás con talón' },
    { name: 'Tichuk-chagui', meaning: 'Patada lateral semicircular con talón' },
    { name: 'Idan-ap-chagui', meaning: 'Patada frontal con salto (ascendente)' },
    { name: 'Idan-iob-chagui', meaning: 'Patada lateral con salto (ascendente)' },
    { name: 'Idan-dolio-chagui', meaning: 'Patada circular con salto (ascendente)' },
    { name: 'Ti-o-ap-chagui', meaning: 'Patada de salto frontal (con desplazamiento)' },
    { name: 'Ti-o-iob-chagui', meaning: 'Patada de salto lateral (con desplazamiento)' },
    { name: 'Ti-o-dolio-chagui', meaning: 'Patada de salto circular (con desplazamiento)' },
    { name: 'Di-dolio-chagui', meaning: 'Patada giratoria circular' },
    { name: 'Di-dolio-iob-chagui', meaning: 'Patada giratoria lateral' },
];

const bodyParts = [
    { name: 'Chong-kwon', meaning: 'Puño' },
    { name: 'Yang', meaning: 'Palma de mano' },
    { name: 'Iu-kwon', meaning: 'Nudillo de dedos' },
    { name: 'Dong-yu-mok', meaning: 'Dorso de muñeca' },
    { name: 'Su-do', meaning: 'Canto de mano' },
    { name: 'Iok-su-do', meaning: 'Canto interno de la mano' },
    { name: 'Kwan-su', meaning: 'Punta de dedos' },
    { name: 'Mu-rub', meaning: 'Rodilla' },
    { name: 'Fal-kum-chi', meaning: 'Codo' },
    { name: 'Mok', meaning: 'Cuello' },
    { name: 'Kwon-do', meaning: 'Canto de puño' },
    { name: 'Iok-kwon-do', meaning: 'Contra canto de puño' },
    { name: 'Wan', meaning: 'Antebrazos' },
    { name: 'Du-gong', meaning: 'Cabeza' },
    { name: 'Yi', meaning: 'Dedo' },
    { name: 'Yok', meaning: 'Pie' },
    { name: 'Yok-yi', meaning: 'Punta de dedos del pie' },
    { name: 'Yok-yung', meaning: 'Metatarso' },
    { name: 'Yok-yang', meaning: 'Planta del pie' },
    { name: 'Yok-do', meaning: 'Canto del pie' },
    { name: 'Yok-chuk', meaning: 'Talón' },
];

const defaultColumns = ['Nombre', 'Significado'];

export const conceptList = [
    {
        title: 'Números',
        hash: 'numeros',
        list: numbers.map(c => ([c.digit, c.corean, c.sinocorean])),
        columns: ['Número', 'Coreano Nativo', 'Sino-Coreano'],
    },
    {
        title: 'Conceptos generales',
        hash: 'conceptos-generales',
        list: concepts.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
    {
        title: 'Hiong (molde matriz)',
        hash: 'hiong',
        list: hiong.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
    {
        title: 'Golpes con manos',
        hash: 'golpes-con-manos',
        list: handKicks.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
    {
        title: 'Defensas',
        hash: 'defensas',
        list: defenses.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
    {
        title: 'Posiciones de avance',
        hash: 'posiciones-de-avance',
        list: forwardPositions.map(c => ([c.name, c.meaning])),
        message: forwardPositionsMessage,
        columns: defaultColumns,
    },
    {
        title: 'Golpes con piernas',
        hash: 'golpes-con-piernas',
        list: legKicks.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
    {
        title: 'Partes del cuerpo',
        hash: 'partes-del-cuerpo',
        list: bodyParts.map(c => ([c.name, c.meaning])),
        columns: defaultColumns,
    },
];
